name: emarsys_sdk
description: The Flutter plug-in for SAP Emarsys Customer Engagement is the official plug-in to help integrate Emarsys into your Flutter application.
version: 2.0.0
homepage: https://github.com/emartech/flutter-plugin-for-sap-emarsys-customer-engagement

environment:
  sdk: '>=2.14.0 <4.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  equatable: ^2.0.5
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  build_version: ^2.1.0
flutter:
  plugin:
    platforms:
      android:
        package: com.emarsys.emarsys_sdk
        pluginClass: EmarsysSdkPlugin
      ios:
        pluginClass: EmarsysSdkPlugin

scripts:
  release:
    - dart pub get
    - dart pub run build_runner build --delete-conflicting-outputs
    - rm example/lib/version.dart
    - $pana-test
  test-flutter:
    -  echo running Flutter unit tests
    -  flutter test
  test-android:
    -  echo running Android unit tests
    -  cd example/android && ./gradlew test
  pretest-ios:
    - open /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app/
  test-ios:
    - echo running iOS unit tests
    - rm -rf ~/Library/Developer/Xcode/DerivedData
    - cd example/ios && pod deintegrate && pod install --no-repo-update --verbose
    - cd example/ios && xcodebuild -workspace Runner.xcworkspace -scheme flutter-plugin-ios-tests -configuration Debug -destination 'platform=iOS Simulator,name=iPhone 14 Pro Max' test
  test:
    - $test-flutter
    - sleep 10s
    - $test-android
    - sleep 10s
    - $test-ios
  pana-test:
    - dart pub global activate pana
    - dart pub global run pana  ./
    